
package GUI;
import DAO.JMMV_BicicletaDAO;
import DAO.JMMV_ClienteDAO;
import DAO.JMMV_ReservaDAO;
import controlador.JMMV_Controlador;
import javax.swing.JOptionPane;
import logica.*;


public class JMMV_Confirmacion extends javax.swing.JDialog {

    private JMMV_Cliente cliente;
    private JMMV_Bicicleta bicicleta;
    private JMMV_Reserva reserva;
    private int picker;
    
    JMMV_Controlador controlador = new JMMV_Controlador();
    
    public JMMV_Confirmacion(java.awt.Frame parent, boolean modal, JMMV_Cliente cliente) {
        super(parent, modal);
        initComponents();
        this.cliente = cliente;
        this.picker = 1;
    }
    
    public JMMV_Confirmacion(java.awt.Frame parent, boolean modal, JMMV_Bicicleta bicicleta) {
        super(parent, modal);
        initComponents();
        this.bicicleta = bicicleta;
        this.picker = 0;
    }
    
    public JMMV_Confirmacion(java.awt.Frame parent, boolean modal, JMMV_Reserva reserva) {
        super(parent, modal);
        initComponents();
        this.reserva = reserva;
        this.picker = 2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        lbPregunta = new javax.swing.JLabel();
        btnNo = new javax.swing.JButton();
        btnSi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNombre.setText("NOMBRE DEL OBJETO");

        lbPregunta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPregunta.setText("¿Estás seguro de querer eliminarlo?");

        btnNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNo.setText("No");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        btnSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSi.setText("Si");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbPregunta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPregunta)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        switch (picker) {
            case 0 -> {
                controlador.JMMV_EliminarBicicleta(bicicleta.getJMMV_Bicicleta_nombre());
                JOptionPane.showMessageDialog(this, "Bicicleta eliminada con exito", "Eliminación exitosa", JOptionPane.ERROR_MESSAGE);
            }
            case 1 -> {
                controlador.JMMV_EliminarCliente(cliente.getJMMV_Cliente_idCliente());
                JOptionPane.showMessageDialog(this, "Cliente eliminado con exito", "Eliminación exitosa", JOptionPane.ERROR_MESSAGE);
            }
            default -> {
                controlador.JMMV_EliminarReserva(reserva.getJMMV_Reserva_idReserva());
                JOptionPane.showMessageDialog(this, "Reserva eliminada con exito", "Eliminación exitosa", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnNoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPregunta;
    // End of variables declaration//GEN-END:variables
}
