
package GUI;

import logica.JMMV_Cliente;
import controlador.JMMV_Controlador;
import java.util.List;
import javax.swing.JOptionPane;


public class JMMV_GestionUsuarios extends javax.swing.JFrame {

    private JMMV_Cliente cliente;
    private JMMV_Controlador controlador = new JMMV_Controlador();
    public JMMV_GestionUsuarios() {
        initComponents();
        CargarComunas();
        this.cliente = null;
        
    }
    
    public JMMV_GestionUsuarios(JMMV_Cliente cliente) {
        initComponents();
        CargarComunas();
        this.cliente = cliente;
        tfNombre.setText(cliente.getJMMV_Cliente_nombres());
        tfApellidoP.setText(cliente.getJMMV_Cliente_apellidoPaterno());
        tfApellidoM.setText(cliente.getJMMV_Cliente_apellidoMaterno());
        tfUser.setText(cliente.getJMMV_Cliente_nomUsuario());
        tfNomCalle.setText(cliente.getJMMV_Cliente_calle());
        tfNumCalle.setText(String.valueOf(cliente.getJMMV_Cliente_numCalle()));
        cBoxComunas.setSelectedItem(cliente.getJMMV_Cliente_comuna());
        pfPass.setText(cliente.getJMMV_Cliente_contrasena());
        tfRun.setText(String.valueOf(cliente.getJMMV_Cliente_run()));
        tfTelefono.setText(String.valueOf(cliente.getJMMV_Cliente_telefono()));
        tfCorreo.setText(cliente.getJMMV_Cliente_correo());
        btnModificar.setVisible(false);
        btnCrear.setText("Modificar");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        lbUser = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        tfUser = new javax.swing.JTextField();
        tfNomCalle = new javax.swing.JTextField();
        lbNomCalle = new javax.swing.JLabel();
        cBoxComunas = new javax.swing.JComboBox<>();
        lbComuna = new javax.swing.JLabel();
        lbPass = new javax.swing.JLabel();
        pfPass = new javax.swing.JPasswordField();
        lbNumCalle = new javax.swing.JLabel();
        tfNumCalle = new javax.swing.JTextField();
        tfApellidoP = new javax.swing.JTextField();
        lbApellidoP = new javax.swing.JLabel();
        tfApellidoM = new javax.swing.JTextField();
        lbApellidoM = new javax.swing.JLabel();
        tfRun = new javax.swing.JTextField();
        lbRun = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        lbTelefono = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        lbCorreo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Agustin\\OneDrive\\Escritorio\\examen_max\\src\\static\\home_50dp_1F1F1F_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        btnHome.setText("Inicio");
        btnHome.setToolTipText("");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        lbUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbUser.setText("Nombre de Usuario");

        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNombre.setText("Nombres");

        btnCrear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnListar.setText("Listar");

        tfUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tfNomCalle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbNomCalle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNomCalle.setText("Nombre de calle");

        cBoxComunas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbComuna.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbComuna.setText("Comuna");

        lbPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPass.setText("Contraseña");

        pfPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbNumCalle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNumCalle.setText("Número de calle");

        tfNumCalle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tfApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbApellidoP.setText("Apellido Paterno");

        tfApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbApellidoM.setText("Apellido Materno");

        tfRun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfRun.setToolTipText("Ingresar RUN sin puntos ni guion. Si su rut termina en K, reemplazelo con un 0. ");

        lbRun.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbRun.setText("RUN");

        tfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTelefono.setText("Telefono");

        tfCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCorreo.setText("Correo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfRun, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbApellidoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfApellidoM)
                                            .addComponent(lbApellidoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfApellidoP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbUser, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                        .addComponent(tfUser, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbNomCalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNomCalle)
                                    .addComponent(cBoxComunas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbComuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pfPass)
                                    .addComponent(lbNumCalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNumCalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHome)
                                .addGap(37, 37, 37)))
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(btnHome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addGap(21, 21, 21)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnListar)
                                .addGap(92, 92, 92))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbNomCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNomCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNumCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNumCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(lbApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cBoxComunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbRun, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrear)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        JMMV_Principal menu = new JMMV_Principal();
        menu.setTitle("Menu");
        menu.setLocationRelativeTo(null);
        menu.setResizable(false);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
            JMMV_Buscador buscador = new JMMV_Buscador(this,true,1);
            buscador.setTitle("Buscar Usuario");
            buscador.setLocationRelativeTo(null);
            buscador.setResizable(false);
            buscador.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(cliente == null) {
            JMMV_Buscador buscador = new JMMV_Buscador(this,true,1);
            buscador.setTitle("Buscar Usuario");
            buscador.setLocationRelativeTo(null);
            buscador.setResizable(false);
            buscador.setVisible(true); 
        } else {
            JMMV_Confirmacion confirmar = new JMMV_Confirmacion(this, true, cliente);
            confirmar.setTitle("Confirmar eliminación");
            confirmar.setLocationRelativeTo(null);
            confirmar.setResizable(false);
            confirmar.setVisible(true);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String nombres = tfNombre.getText();
        String apellidoP = tfApellidoP.getText();
        String apellidoM = tfApellidoM.getText();
        String user = tfUser.getText();
        String run = tfRun.getText();
        String correo = tfCorreo.getText();
        String nomCalle = tfNomCalle.getText();
        String numCalle = tfNumCalle.getText();
        String comuna = (String)cBoxComunas.getSelectedItem();
        String pass = new String(pfPass.getPassword());
        String telefono = tfTelefono.getText();
        
        if (nombres.isEmpty() || apellidoP.isEmpty() || apellidoM.isEmpty() ||
            user.isEmpty() || run.isEmpty() || correo.isEmpty() ||
            nomCalle.isEmpty() || numCalle.isEmpty() || comuna.isEmpty() ||
            pass.isEmpty() || telefono.isEmpty()) {
            
             JOptionPane.showMessageDialog(
                    this,
                    "Todos los campos son obligatorios.",
                    "Campos vacios",
                    JOptionPane.ERROR_MESSAGE
            );

            return;
        }
        
        try {
            int runConv = Integer.parseInt(run);
            int numCalleConv = Integer.parseInt(numCalle);
            int telefonoConv = Integer.parseInt(telefono);
            
            if (runConv < 10000000 || numCalleConv <= 0 || telefonoConv <= 900000000) {
                JOptionPane.showMessageDialog(
                        this,
                        "El RUN, número de calle o teléfono contiene valores inválidos.",
                        "Valores invalidos",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }
            
            if (cliente == null) {
                cliente = new JMMV_Cliente(user, pass, correo, runConv, nombres, apellidoP, apellidoM, comuna, nomCalle, numCalleConv, telefonoConv);
                
                System.out.println("Test | nombre de usuario a crear: "+cliente.getJMMV_Cliente_nomUsuario());
                controlador.JMMV_AgregarCliente(cliente);
                JOptionPane.showMessageDialog(this, "Usuario agregado con éxito", "Usuario Agregado", JOptionPane.INFORMATION_MESSAGE);
                //problema: no está cerrando el cliente después de guardar cliente nuevo. 
                //Ahora cliente no es NULL y siempre entrará en el ELSE y hará un ingreso/actualización "falso" 
                //que no se hace en la BD.
                //solución:
                this.cliente = null;
                
            } else {
                System.out.println("Test | id usuario BOTON crear 1 : "+cliente.getJMMV_Cliente_idUsuario());
                cliente.setJMMV_Cliente_nombres(nombres);
                cliente.setJMMV_Cliente_apellidoPaterno(apellidoP);
                cliente.setJMMV_Cliente_apellidoMaterno(apellidoM);
                cliente.setJMMV_Cliente_nomUsuario(user);
                cliente.setJMMV_Cliente_run(runConv);
                cliente.setJMMV_Cliente_correo(correo);
                cliente.setJMMV_Cliente_calle(nomCalle);
                cliente.setJMMV_Cliente_numCalle(numCalleConv);
                cliente.setJMMV_Cliente_comuna(comuna);
                cliente.setJMMV_Cliente_contrasena(pass);
                cliente.setJMMV_Cliente_telefono(telefonoConv);
                System.out.println("Test | ID usuario BOTON crear 2 : "+cliente.getJMMV_Cliente_idUsuario());
                controlador.JMMV_ActualizarCliente(cliente);
                JOptionPane.showMessageDialog(this, "Usuario actualizado con éxito", "Usuario Actualizado", JOptionPane.INFORMATION_MESSAGE);
                
            }
            
            
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                        this,
                        "El RUN, número de calle o teléfono contiene valores inválidos.",
                        "Valores invalidos",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
        }
            
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void CargarComunas() {
        
        List<String> comunas = controlador.JMMV_ObtenerComunasActivas();

        for (String comuna : comunas) {
            cBoxComunas.addItem(comuna);
        }
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cBoxComunas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbApellidoM;
    private javax.swing.JLabel lbApellidoP;
    private javax.swing.JLabel lbComuna;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbNomCalle;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNumCalle;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbRun;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JTextField tfApellidoM;
    private javax.swing.JTextField tfApellidoP;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfNomCalle;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNumCalle;
    private javax.swing.JTextField tfRun;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
