package GUI;

import controlador.JMMV_Controlador;
import java.util.List;
import javax.swing.JOptionPane;
import logica.JMMV_Bicicleta;

public class JMMV_GestionBicicleta extends javax.swing.JFrame {

    private JMMV_Bicicleta bicicleta;
    JMMV_Controlador controlador = new JMMV_Controlador();

    public JMMV_GestionBicicleta() {
        initComponents();
        JMMV_CargarTipos();
        this.bicicleta = null;
    }

    public JMMV_GestionBicicleta(JMMV_Bicicleta bicicleta) {
        initComponents();
        JMMV_CargarTipos();
        this.bicicleta = bicicleta;
        btnModificar.setText("Seleccionar otro");
        btnCrear.setText("Modificar");
        tfNombre.setText(bicicleta.getJMMV_Bicicleta_nombre());
        cBoxTipos.setSelectedItem(bicicleta.getJMMV_Bicicleta_tipoBicicleta());
        chBoxDisponible.setSelected(bicicleta.isJMMV_Bicicleta_estaDisponible());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        lbTipo = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        lbDisponibilidad = new javax.swing.JLabel();
        chBoxDisponible = new javax.swing.JCheckBox();
        btnCrear = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        cBoxTipos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHome.setText("Inicio");
        btnHome.setToolTipText("");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        lbTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTipo.setText("Tipo");

        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNombre.setText("Nombre");

        lbDisponibilidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbDisponibilidad.setText("Disponibilidad:");

        chBoxDisponible.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chBoxDisponible.setText("Disponible");

        btnCrear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        cBoxTipos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNombre)
                            .addComponent(lbTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cBoxTipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chBoxDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDisponibilidad)
                    .addComponent(chBoxDisponible))
                .addGap(45, 45, 45)
                .addComponent(btnCrear)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        JMMV_Principal menu = new JMMV_Principal();
        menu.setTitle("Menu");
        menu.setLocationRelativeTo(null);
        menu.setResizable(false);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (bicicleta == null) {
            JMMV_Buscador buscador = new JMMV_Buscador(this, true, 0, 1);
            buscador.setTitle("Buscar Bicicleta");
            buscador.setLocationRelativeTo(null);
            buscador.setResizable(false);
            buscador.setVisible(true);
            this.dispose();
        } else {
            JMMV_Confirmacion confirmar = new JMMV_Confirmacion(this, true, bicicleta);
            confirmar.setTitle("Confirmar eliminación");
            confirmar.setLocationRelativeTo(null);
            confirmar.setResizable(false);
            confirmar.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        JMMV_ListadoBicicleta listado = new JMMV_ListadoBicicleta();
        listado.setTitle("Buscar Bicicleta");
        listado.setLocationRelativeTo(null);
        listado.setResizable(false);
        listado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String nombre = tfNombre.getText();
        String tipo = (String) cBoxTipos.getSelectedItem();
        boolean disponible = chBoxDisponible.isSelected();

        if (nombre.isEmpty() || tipo.equals("-1")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Todos los campos son obligatorios.",
                    "Campos vacios",
                    JOptionPane.ERROR_MESSAGE
            );

            return;
        }
        
        if(controlador.JMMV_NombreBicicletaYaRegistrado(nombre)) {
            JOptionPane.showMessageDialog(
                            this,
                            "El Nombre de la bicicleta ya se encuentra registrado, por favor intente con otro.",
                            "Nombre de bicicleta ya resgitrado",
                            JOptionPane.ERROR_MESSAGE
                    );
                    return;
        }

        try {
            if (bicicleta == null) {
                //solo se eliminó el valor de la descripción
                bicicleta = new JMMV_Bicicleta(nombre, tipo, disponible, true);
                boolean exito = controlador.JMMV_AgregarBicicleta(bicicleta);
                if (!exito) {
                    JOptionPane.showMessageDialog(this, "Bicicleta duplicada, intente con otro nombre", "BICICLETA DUPLICADA", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Bicicleta agregada con éxito", "Bicicleta Agregada", JOptionPane.INFORMATION_MESSAGE);
                    this.bicicleta = null;
                    JMMV_CompositorLimpio();
                }

            } else {
                bicicleta.setJMMV_Bicicleta_nombre(nombre);
                bicicleta.setJMMV_Bicicleta_tipoBicicleta(tipo);
                bicicleta.setJMMV_Bicicleta_estaDisponible(disponible);
                boolean exito = controlador.JMMV_ActualizarBicicleta(bicicleta);
                if (!exito) {
                    JOptionPane.showMessageDialog(this, "No se pudo actualizar la bicicleta, intente nuevamente", "FALLO AL ACTUALIZAR", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Bicicleta actualizada con éxito", "Bicicleta Actualizada", JOptionPane.INFORMATION_MESSAGE);
                    JMMV_CompositorLimpio();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Existe un problema con los datos, intente nuevamente.",
                    "Valores invalidos",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        JMMV_ListadoBicicleta listado = new JMMV_ListadoBicicleta();
        listado.setTitle("Listado de Bicicletas");
        listado.setLocationRelativeTo(null);
        listado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListarActionPerformed

    private void JMMV_CargarTipos() {

        List<String> tipos = controlador.JMMV_ObtenerTiposDeBicicletaActivos();

        for (String tipo : tipos) {
            cBoxTipos.addItem(tipo);
        }
    }

    private void JMMV_CompositorLimpio() {
        JMMV_GestionBicicleta gestionBicicleta = new JMMV_GestionBicicleta();
        gestionBicicleta.setTitle("Gestión Bicicleta");
        gestionBicicleta.setLocationRelativeTo(null);
        gestionBicicleta.setResizable(false);
        gestionBicicleta.setVisible(true);
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cBoxTipos;
    private javax.swing.JCheckBox chBoxDisponible;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDisponibilidad;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
