
package GUI;


import controlador.JMMV_Controlador;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import logica.JMMV_Cliente;
import logica.JMMV_Reserva;
import logica.JMMV_TimeMachine;


public class JMMV_GestionReserva extends javax.swing.JFrame {

    private JMMV_Reserva reserva;
    JMMV_Controlador controlador = new JMMV_Controlador();
    JMMV_TimeMachine timeMachine = new JMMV_TimeMachine();
    Date comprobacion = new Date(0);
    
    public JMMV_GestionReserva() {
        initComponents();
        CargarBicicletas();
        CargarClientes();
        dcInicio.setDate(comprobacion);
        dcTermino.setDate(comprobacion);
        this.reserva = null;
    }

    public JMMV_GestionReserva(JMMV_Reserva reserva) {
        initComponents();
        CargarBicicletas();
        CargarClientes();
        this.reserva = reserva;
        cBoxBicicletas.setSelectedItem(reserva.getJMMV_Reserva_nomBicicleta());
        cBoxClientes.setSelectedItem(reserva.getJMMV_Reserva_nomCliente());
        dcInicio.setDate(timeMachine.asDate(reserva.getJMMV_Reserva_fechaInicio()));
        dcTermino.setDate(timeMachine.asDate(reserva.getJMMV_Reserva_fechaFin()));
         
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        lbBicicletas = new javax.swing.JLabel();
        lbClientes = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        cBoxClientes = new javax.swing.JComboBox<>();
        cBoxBicicletas = new javax.swing.JComboBox<>();
        lbInicio = new javax.swing.JLabel();
        dcInicio = new com.toedter.calendar.JDateChooser();
        lbTermino = new javax.swing.JLabel();
        dcTermino = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Agustin\\OneDrive\\Escritorio\\examen_max\\src\\static\\home_50dp_1F1F1F_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        btnHome.setText("Inicio");
        btnHome.setToolTipText("");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        lbBicicletas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbBicicletas.setText("Bicicletas");

        lbClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbClientes.setText("Clientes");

        btnCrear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnListar.setText("Listar");

        cBoxClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cBoxBicicletas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbInicio.setText("Fecha Inicio");

        lbTermino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTermino.setText("Fecha Termino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbBicicletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cBoxBicicletas, 0, 225, Short.MAX_VALUE)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(dcInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(72, 72, 72))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnHome)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addGap(11, 11, 11)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnListar)
                        .addGap(30, 30, 30)
                        .addComponent(btnHome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTermino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbBicicletas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cBoxBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(btnCrear)))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        JMMV_Principal menu = new JMMV_Principal();
        menu.setTitle("Menu");
        menu.setLocationRelativeTo(null);
        menu.setResizable(false);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(reserva == null) {
            JMMV_Buscador buscador = new JMMV_Buscador(this,true,2);
            buscador.setTitle("Buscar Reserva");
            buscador.setLocationRelativeTo(null);
            buscador.setResizable(false);
            buscador.setVisible(true); 
        } else {
            JMMV_Confirmacion confirmar = new JMMV_Confirmacion(this, true, reserva);
            confirmar.setTitle("Confirmar eliminación");
            confirmar.setLocationRelativeTo(null);
            confirmar.setResizable(false);
            confirmar.setVisible(true);
        }
                             
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
            JMMV_Buscador buscador = new JMMV_Buscador(this,true,2);
            buscador.setTitle("Buscar Reserva");
            buscador.setLocationRelativeTo(null);
            buscador.setResizable(false);
            buscador.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String nombres = (String)cBoxClientes.getSelectedItem();
        String bicicleta = (String)cBoxBicicletas.getSelectedItem();
        Date fechaInic = dcInicio.getDate();
        Date fechaTer = dcTermino.getDate();
        
        if (nombres.isEmpty() || bicicleta.isEmpty() || fechaInic.equals(comprobacion) || fechaTer.equals(comprobacion)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Todos los campos son obligatorios.",
                    "Campos vacios",
                    JOptionPane.ERROR_MESSAGE
            );
        } 
        
        try {
            LocalDate fechaInicConv = timeMachine.asLocalDate(fechaInic);
            LocalDate fechaTerConv = timeMachine.asLocalDate(fechaTer);
            List <JMMV_Cliente> cliente = controlador.JMMV_ObtenerClientePorNombre(nombres);
            int idCliente = cliente.get(0).getJMMV_Cliente_idCliente();
            int idBicicleta = controlador.JMMV_ObtenerBicicletaPorNombre(bicicleta);
            
            if(reserva == null) {
                reserva = new JMMV_Reserva(idCliente, nombres, idBicicleta, bicicleta, fechaInicConv, fechaTerConv);
                controlador.JMMV_AgregarReserva(reserva);
                JOptionPane.showMessageDialog(this, "Reserva agregada con éxito", "Reserva Agregada", JOptionPane.INFORMATION_MESSAGE);
            } else {
                reserva.setJMMV_Reserva_nomCliente(nombres);
                reserva.setJMMV_Reserva_idCliente(idCliente);
                reserva.setJMMV_Reserva_nomBicicleta(bicicleta);
                reserva.setJMMV_Reserva_idBicicleta(idBicicleta);
                reserva.setJMMV_Reserva_fechaInicio(fechaInicConv);
                reserva.setJMMV_Reserva_fechaFin(fechaTerConv);
                controlador.JMMV_ActualizarReserva(reserva);
                JOptionPane.showMessageDialog(this, "Reserva actualizada con éxito", "Resera Actualizada", JOptionPane.INFORMATION_MESSAGE);
            }
            
            
        } catch (DateTimeException e) {
            JOptionPane.showMessageDialog(
                        this,
                        "Existe un error en la selección de fechas, favor reintentar.",
                        "Valores invalidos",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
        }
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void CargarBicicletas() {
        
        List<String> bicicletas = controlador.JMMV_ObtenerNombresBicicletasActivas();

        for (String bicicleta : bicicletas) {
            cBoxBicicletas.addItem(bicicleta);
        }
    }
    
    private void CargarClientes() {
        
        List<String> clientes = controlador.JMMV_ObtenerNombresCompletosClientesActivos();

        for (String cliente : clientes) {
            cBoxClientes.addItem(cliente);
        }
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cBoxBicicletas;
    private javax.swing.JComboBox<String> cBoxClientes;
    private com.toedter.calendar.JDateChooser dcInicio;
    private com.toedter.calendar.JDateChooser dcTermino;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBicicletas;
    private javax.swing.JLabel lbClientes;
    private javax.swing.JLabel lbInicio;
    private javax.swing.JLabel lbTermino;
    // End of variables declaration//GEN-END:variables
}
