package GUI;

import controlador.JMMV_Controlador;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import logica.JMMV_Cliente;
import logica.JMMV_Reserva;
import logica.JMMV_TimeMachine;

public class JMMV_GestionReserva extends javax.swing.JFrame {

    private JMMV_Reserva reserva;
    JMMV_Controlador controlador = new JMMV_Controlador();
    JMMV_TimeMachine timeMachine = new JMMV_TimeMachine();
    Date comprobacion = new Date();

    public JMMV_GestionReserva() {
        initComponents();
        JMMV_CargarBicicletas();
        JMMV_CargarClientes();
        comprobacion = timeMachine.JMMV_asDate(LocalDate.now());
        dcInicio.setDate(comprobacion);
        dcTermino.setDate(comprobacion);
        this.reserva = null;
    }

    public JMMV_GestionReserva(JMMV_Reserva reserva) {
        initComponents();
        JMMV_CargarBicicletas();
        JMMV_CargarClientes();
        System.out.println("aca entre 2");
        this.reserva = reserva;
        btnCrear.setText("Modificar");
        btnModificar.setText("Seleccionar otro");
        comprobacion = timeMachine.JMMV_asDate(LocalDate.now());
        cBoxBicicletas.setSelectedItem(reserva.getJMMV_Reserva_nomBicicleta());
        cBoxClientes.setSelectedItem(reserva.getJMMV_Reserva_nomCliente());
        dcInicio.setDate(timeMachine.JMMV_asDate(reserva.getJMMV_Reserva_fechaInicio()));
        dcTermino.setDate(timeMachine.JMMV_asDate(reserva.getJMMV_Reserva_fechaFin()));

    }

    public JMMV_GestionReserva(List<JMMV_Reserva> reservas) {

        initComponents();
        JMMV_CargarBicicletas();
        JMMV_CargarClientesDeReserva(reservas);
        System.out.println("aca entre 3");
        comprobacion = timeMachine.JMMV_asDate(LocalDate.now());
        dcInicio.setDate(comprobacion);
        dcTermino.setDate(comprobacion);
        this.reserva = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        lbBicicletas = new javax.swing.JLabel();
        lbClientes = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        cBoxClientes = new javax.swing.JComboBox<>();
        cBoxBicicletas = new javax.swing.JComboBox<>();
        lbInicio = new javax.swing.JLabel();
        dcInicio = new com.toedter.calendar.JDateChooser();
        lbTermino = new javax.swing.JLabel();
        dcTermino = new com.toedter.calendar.JDateChooser();
        btnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logica/stat/home_50dp_1F1F1F_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btnHome.setText("Inicio");
        btnHome.setToolTipText("");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        lbBicicletas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbBicicletas.setText("Bicicletas");

        lbClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbClientes.setText("Clientes");

        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        cBoxClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cBoxBicicletas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbInicio.setText("Fecha Inicio");

        dcInicio.setForeground(new java.awt.Color(255, 255, 255));
        dcInicio.setMinSelectableDate(new java.util.Date(1735704090000L));

        lbTermino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTermino.setText("Fecha Termino");

        dcTermino.setForeground(new java.awt.Color(255, 255, 255));

        btnCrear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbInicio)
                            .addComponent(cBoxBicicletas, 0, 373, Short.MAX_VALUE)
                            .addComponent(cBoxClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dcInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTermino, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(dcTermino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHome)
                                .addGap(100, 100, 100))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(cBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lbBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBoxBicicletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(dcTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHome)
                        .addGap(35, 35, 35)
                        .addComponent(btnCrear)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        JMMV_Principal menu = new JMMV_Principal();
        menu.setTitle("Menu");
        menu.setLocationRelativeTo(null);
        menu.setResizable(false);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (reserva == null) {
            JMMV_Buscador buscador = new JMMV_Buscador(this, true, 2, 1);
            buscador.setTitle("Buscar Reserva");
            buscador.setLocationRelativeTo(null);
            buscador.setResizable(false);
            buscador.setVisible(true);
            this.dispose();
        } else {
            JMMV_Confirmacion confirmar = new JMMV_Confirmacion(this, true, reserva);
            confirmar.setTitle("Confirmar eliminación");
            confirmar.setLocationRelativeTo(null);
            confirmar.setResizable(false);
            confirmar.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        JMMV_ListadoReservas listado = new JMMV_ListadoReservas();
        listado.setTitle("Buscar Reserva");
        listado.setLocationRelativeTo(null);
        listado.setResizable(false);
        listado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String nombres = (String) cBoxClientes.getSelectedItem();
        String bicicleta = (String) cBoxBicicletas.getSelectedItem();
        Date fechaInic = dcInicio.getDate();
        Date fechaTer = dcTermino.getDate();

        if (nombres.isEmpty() || bicicleta.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Todos los campos son obligatorios.",
                    "Campos vacios",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        try {
            LocalDate fechaInicConv = timeMachine.JMMV_asLocalDate(fechaInic);
            LocalDate fechaTerConv = timeMachine.JMMV_asLocalDate(fechaTer);
            List<JMMV_Cliente> cliente = controlador.JMMV_ObtenerClienteDeCBox(nombres);
            int idCliente = cliente.get(0).getJMMV_Cliente_idCliente();
            int idBicicleta = controlador.JMMV_ObtenerIdBicicletaPorNombre(bicicleta);
            int numReservas = controlador.JMMV_ContarReservasVigentesDeClientes(cliente.get(0).getJMMV_Cliente_nombres());

            if (numReservas == -1) {
                return;
            } else {
                if (reserva == null) {
                    if (numReservas > 0) {
                        JOptionPane.showMessageDialog(
                                this,
                                "El cliente ya cuenta con una reserva activa, intente con otro",
                                "Reserva activa",
                                JOptionPane.ERROR_MESSAGE
                        );
                        return;
                    }
                    
                    if (fechaTer.before(comprobacion)) {
                        JOptionPane.showMessageDialog(
                                this,
                                "La fecha de termino no puede ser inferior a la fecha de hoy. Reintente con una fecha nueva.",
                                "ERROR DE FECHA",
                                JOptionPane.ERROR_MESSAGE
                        );
                        return;
                    }
                    reserva = new JMMV_Reserva(idCliente, nombres, idBicicleta, bicicleta, fechaInicConv, fechaTerConv);
                    boolean exito = controlador.JMMV_AgregarReserva(reserva);
                    if (!exito) {
                        JOptionPane.showMessageDialog(this, "No se pudo crear la reserva, intente nuevamene", "ERROR AL AGREGAR RESERVA", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Reserva agregada con éxito", "Reserva Agregada", JOptionPane.INFORMATION_MESSAGE);
                        JMMV_CompositorLimpio();
                    }

                } else {
                    
                    if (fechaTer.before(comprobacion)) {
                        JOptionPane.showMessageDialog(
                                this,
                                "La fecha de termino no puede ser inferior a la fecha de hoy. Reintente con una fecha nueva.",
                                "ERROR DE FECHA",
                                JOptionPane.ERROR_MESSAGE
                        );
                        return;
                    }
                    
                    reserva.setJMMV_Reserva_nomCliente(nombres);
                    reserva.setJMMV_Reserva_idCliente(idCliente);
                    reserva.setJMMV_Reserva_nomBicicleta(bicicleta);
                    reserva.setJMMV_Reserva_idBicicleta(idBicicleta);
                    reserva.setJMMV_Reserva_fechaInicio(fechaInicConv);
                    reserva.setJMMV_Reserva_fechaFin(fechaTerConv);
                    boolean exito = controlador.JMMV_ActualizarReserva(reserva);
                    if (!exito) {
                        JOptionPane.showMessageDialog(this, "No se pudo acualizar la reserva, intente nuevamene", "ERROR AL ACTUALIZAR RESERVA", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Reserva actualizada con éxito", "Reserva Actualizada", JOptionPane.INFORMATION_MESSAGE);
                        JMMV_CompositorLimpio();
                    }

                }

            }

        } catch (DateTimeException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Existe un error en la selección de fechas, favor reintentar.",
                    "Valores invalidos",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        JMMV_ListadoReservas listado = new JMMV_ListadoReservas();
        listado.setTitle("Listado de Reservas");
        listado.setLocationRelativeTo(null);
        listado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListarActionPerformed

    private void JMMV_CargarBicicletas() {

        List<String> bicicletas = controlador.JMMV_ObtenerNombresBicicletasActivas();

        for (String bicicleta : bicicletas) {
            cBoxBicicletas.addItem(bicicleta);
        }
    }

    private void JMMV_CargarClientes() {

        List<String> clientes = controlador.JMMV_ObtenerNombresCompletosClientesActivos();

        for (String cliente : clientes) {
            cBoxClientes.addItem(cliente);
        }
    }

    private void JMMV_CargarClientesDeReserva(List<JMMV_Reserva> reservas) {
        for (JMMV_Reserva reserva : reservas) {
            cBoxClientes.addItem(reserva.getJMMV_Reserva_nomCliente());
        }
    }

    private void JMMV_CompositorLimpio() {
        JMMV_GestionReserva gestionReservas = new JMMV_GestionReserva();
        gestionReservas.setTitle("Gestion Reservas");
        gestionReservas.setLocationRelativeTo(null);
        gestionReservas.setResizable(false);
        gestionReservas.setVisible(true);
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cBoxBicicletas;
    private javax.swing.JComboBox<String> cBoxClientes;
    private com.toedter.calendar.JDateChooser dcInicio;
    private com.toedter.calendar.JDateChooser dcTermino;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBicicletas;
    private javax.swing.JLabel lbClientes;
    private javax.swing.JLabel lbInicio;
    private javax.swing.JLabel lbTermino;
    // End of variables declaration//GEN-END:variables
}
