/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.JMMV_BicicletaDAO;
import DAO.JMMV_ClienteDAO;
import DAO.JMMV_ReservaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import logica.JMMV_Cliente;

/**
 *
 * @author Agustin
 */
public class JMMV_Buscador extends javax.swing.JDialog {

    private int seleccion;
    private JMMV_ClienteDAO clienteDAO;
    private JMMV_BicicletaDAO BicicletaDAO;
    private JMMV_ReservaDAO ReservaDAO;
    public JMMV_Buscador(java.awt.Frame parent, boolean modal,int seleccion) {
        super(parent, modal);
        initComponents();
        switch (seleccion) {
            case 0 ->{lbBuscar.setText("Buscar Bicicleta por nombre"); this.seleccion = seleccion;}
            case 1 -> {lbBuscar.setText("Buscar Cliente por nombre:"); this.seleccion = seleccion;}
            case 2 -> {lbBuscar.setText("Buscar Reserva por nombre de cliente;"); this.seleccion = seleccion;}
            default -> {
                JOptionPane.showMessageDialog(this,"Error de inicialización", "ERROR DE SELECCION", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbBuscar = new javax.swing.JLabel();
        tfBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbBuscar.setText("Buscar \"algo\" por nombre:");

        tfBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfBuscar.setText("Nombre");

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbBuscar)
                .addGap(18, 18, 18)
                .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(seleccion == 0) {
            //
        } else if (seleccion == 1) {
            List <JMMV_Cliente> cliente = clienteDAO.JMMV_ObtenerClientePorNombre(tfBuscar.getText().toUpperCase());
            if(cliente.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontro al cliente, intente nuevamente", "CLIENTE NO ENCONTRADO", JOptionPane.ERROR_MESSAGE);
            } else {
                if (cliente.size() > 1) {
                    int run = Integer.parseInt(JOptionPane.showInputDialog(this, "Existe más de un usuario con esta combinación de nombres, favor ingresar el run del cliente."));
                    List <JMMV_Cliente> clienteRun = clienteDAO.JMMV_ObtenerClientePorRun(run);
                    System.out.println("Cliente encontrado");
                    JMMV_Confirmacion confirmar = new JMMV_Confirmacion(null, true, clienteRun.get(0));
                    this.dispose();
                } else {
                    System.out.println("Cliente encontrado");
                    JMMV_Confirmacion confirmar = new JMMV_Confirmacion(null, true, cliente.get(0));
                } 
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JTextField tfBuscar;
    // End of variables declaration//GEN-END:variables
}
